### Minimizing QM of MEOH

In [1]:
import numpy as np
from scipy.optimize import minimize
from pyscf import scf, qmmm, gto
from pyscf.tools import cubegen
from pyscf.geomopt.geometric_solver import optimize
import MDAnalysis as mda
import sys; sys.path.append('/home/chemistry/QMMM/')
import visualize_QMMM as vQ
import SCF_helpers as Sh
from importlib import reload  # Python 3.4+
import pickle
import os
import py3Dmol
import time
from pyscf.geomopt.geometric_solver import optimize
print(optimize.__module__)

In [2]:
# ============================================================
# Constants
# ============================================================

HARTREE_TO_KJMOL = 2625.49962

In [3]:
picklefile = "oxazole7.pkl"
cube_folder = "cubes_optimized"

In [4]:
# # Creates a PySCF Mole object describing the quantum-mechanical system that PySCF will calculate
mol = gto.M(
    atom='../oxazole7.xyz',
    basis='6-31G',
    charge=0,
    spin=0,
    verbose=4
)

System: uname_result(system='Linux', node='Cas2', release='6.1.177-1-MANJARO', version='#1 SMP PREEMPT_DYNAMIC Sat Jul  4 22:18:29 UTC 2026', machine='x86_64')  Threads 32
Python 3.14.6 (main, Jun 15 2026, 11:36:54) [GCC 16.1.1 20260430]
numpy 2.5.1  scipy 1.18.0  h5py 3.16.0
Date: Mon Sep 28 09:41:44 2026
PySCF version 2.14.0
PySCF path  /home/chemistry/venvs/jupyter/lib/python3.14/site-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 87
[INPUT] num. electrons = 354
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 C      9.151000000000   4.093000000000   7.220000000000 AA   17.292883765895   7.734649027845  13.643822619360 Bohr   0.0
[INPUT]  2 C      9.108000000000   2.574000000000   7.426000000000 AA   17.211625542539   4.86415504

In [5]:
# SCF calculation
mf = scf.RHF(mol)

def stop_after_n(envs):
    if envs.get("cycle", 0) >= 5:
        raise StopIteration

# Start timing
start_time = time.time()

# Geometry optimization
mol_opt = optimize(mf, maxsteps=6, callback=stop_after_n)

# End timing
print("Optimization time:", time.time() - start_time)

Create scanner for <class 'pyscf.grad.rhf.Gradients'>
Create scanner for <class 'pyscf.scf.hf.RHF'>


geometric-optimize called with the following command line:
/home/chemistry/venvs/jupyter/lib/python3.14/site-packages/ipykernel_launcher.py -f /home/chemistry/.local/share/jupyter/runtime/kernel-f647d237-4749-40da-9709-d002dadb8c40.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   9.151000   4.093000   7.220000    0.000000  0.000000  0.000000
   C   9.108000   2.574000   7.426000    0.000000  0.000000  0.000000
   C  10.370000   1.893000   6.879000    0.000000  0.000000  0.000000
   O  10.492000   2.077000   5.468000    0.000000  0.000000  0.000000
   C   9.702000   1.452000   4.488000    0.000000  0.000000  0.000000
   C   8.795000   0.420000   4.785000    0.000000  0.000000  0.000000
   C   8.003000  -0.160000   3.777000    0.000000  0.000000  0.000000
   C   7.008000  -1.223000   4.167000    0.000000  0.000000  0.000000
   C   8.151000   0.279000   2.435000    0.000000  0.000000  0.000000
   C   9.067000   1.308000   2.153000    0.000000  0.000000  0.000000
   C   9.834000   1.881000   3.167000    0.000000  0.000000  0.000000
   C   7.351000  -0.282000   1.319000    0.000000  0.000000  0.000000
   O   7.106000   0.430000   0.3

Step    0 : Gradient = 3.676e-02/1.129e-01 (rms/max) Energy = -2552.6330561411
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 2.30000e-02 ... 6.29961e-01 7.88167e-01 7.88883e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   9.019836   4.191839   7.155076   -0.131164  0.098839 -0.064924
   C   8.986567   2.676934   7.394301   -0.121433  0.102934 -0.031699
   C  10.258469   1.995397   6.870888   -0.111531  0.102397 -0.008112
   O  10.388240   2.151111   5.457216   -0.103760  0.074111 -0.010784
   C   9.613234   1.498592   4.483294   -0.088766  0.046592 -0.004706
   C   8.715242   0.460112   4.786267   -0.079758  0.040112  0.001267
   C   7.940172  -0.144961   3.779413   -0.062828  0.015039  0.002413
   C   6.954124  -1.214121   4.175707   -0.053876  0.008879  0.008707
   C   8.096262   0.275846   2.432469   -0.054738 -0.003154 -0.002531
   C   9.002746   1.311301   2.145019   -0.064254  0.003301 -0.007981
   C   9.752727   1.908337   3.157262   -0.081273  0.027337 -0.009738
   C   7.315341  -0.308873   1.315065   -0.035659 -0.026873 -0.003935
   O   7.075213   0.390225   0.2

Step    1 : Displace = 9.954e-02/2.053e-01 (rms/max) Trust = 1.000e-01 (=) Grad = 3.641e-02/1.116e-01 (rms/max) E (change) = -2552.6510481853 (-1.799e-02) Quality = 1.059
Eigenvalues below 1.0000e-05 (-1.4298e+01) - returning guess
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 2.30000e-02 ... 6.29961e-01 7.88167e-01 7.88883e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   8.820773   4.320577   7.063246   -0.199063  0.128738 -0.091830
   C   8.805349   2.811890   7.344268   -0.181218  0.134956 -0.050033
   C  10.093118   2.135516   6.853230   -0.165351  0.140119 -0.017659
   O  10.235232   2.255871   5.437341   -0.153008  0.104759 -0.019874
   C   9.483420   1.565941   4.471199   -0.129814  0.067349 -0.012095
   C   8.600265   0.516713   4.782071   -0.114976  0.056601 -0.004196
   C   7.850278  -0.123103   3.777218   -0.089894  0.021857 -0.002195
   C   6.878845  -1.202777   4.181539   -0.075279  0.011344  0.005832
   C   8.016979   0.274243   2.424397   -0.079283 -0.001603 -0.008072
   C   8.908081   1.320431   2.129658   -0.094666  0.009131 -0.015361
   C   9.632953   1.950895   3.139193   -0.119774  0.042558 -0.018068
   C   7.263566  -0.343823   1.306012   -0.051775 -0.034950 -0.009053
   O   7.028303   0.337288   0.2

Step    2 : Displace = 1.404e-01/2.850e-01 (rms/max) Trust = 1.414e-01 (+) Grad = 3.566e-02/1.102e-01 (rms/max) E (change) = -2552.6750833418 (-2.404e-02) Quality = 1.002
Hessian Eigenvalues: 9.92982e-03 2.30000e-02 2.30000e-02 ... 7.71445e-01 7.88521e-01 1.18592e+01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   8.509882   4.487455   6.933058   -0.310891  0.166877 -0.130188
   C   8.528498   2.987993   7.264357   -0.276851  0.176102 -0.079911
   C   9.841281   2.329997   6.815227   -0.251837  0.194481 -0.038003
   O  10.001951   2.407845   5.398354   -0.233281  0.151975 -0.038987
   C   9.286627   1.666625   4.442835   -0.196792  0.100684 -0.028364
   C   8.429333   0.598999   4.764730   -0.170932  0.082286 -0.017340
   C   7.717271  -0.089570   3.764038   -0.133008  0.033534 -0.013181
   C   6.771300  -1.187818   4.179199   -0.107546  0.014959 -0.002340
   C   7.896764   0.278235   2.404545   -0.120215  0.003992 -0.019852
   C   8.761482   1.342845   2.099500   -0.146599  0.022413 -0.030158
   C   9.448541   2.020416   3.104069   -0.184412  0.069521 -0.035124
   C   7.183951  -0.387160   1.286705   -0.079614 -0.043337 -0.019307
   O   6.951600   0.268293   0.2

Step    3 : Displace = 2.037e-01/4.101e-01 (rms/max) Trust = 2.000e-01 (+) Grad = 3.467e-02/1.084e-01 (rms/max) E (change) = -2552.7013564153 (-2.627e-02) Quality = 0.871
Hessian Eigenvalues: 2.29491e-02 2.30000e-02 2.30000e-02 ... 7.69239e-01 7.88583e-01 1.58349e+01



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   8.003032   4.665544   6.777759   -0.506849  0.178089 -0.155300
   C   8.099180   3.174683   7.142089   -0.429318  0.186691 -0.122268
   C   9.453178   2.576278   6.731584   -0.388103  0.246280 -0.083643
   O   9.640133   2.626348   5.316516   -0.361818  0.218503 -0.081838
   C   8.984676   1.822802   4.369741   -0.301951  0.156177 -0.073093
   C   8.179058   0.719866   4.704966   -0.250275  0.120867 -0.059765
   C   7.524251  -0.032267   3.711465   -0.193020  0.057302 -0.052573
   C   6.629357  -1.168242   4.139009   -0.141943  0.019576 -0.040189
   C   7.711053   0.308929   2.346578   -0.185711  0.030694 -0.057968
   C   8.524297   1.409201   2.028773   -0.237184  0.066356 -0.070727
   C   9.154732   2.149190   3.025520   -0.293809  0.128775 -0.078550
   C   7.056642  -0.419669   1.232829   -0.127309 -0.032509 -0.053876
   O   6.813112   0.198383   0.1

Step    4 : Displace = 2.923e-01/6.080e-01 (rms/max) Trust = 2.828e-01 (+) Grad = 3.417e-02/1.049e-01 (rms/max) E (change) = -2552.7671907549 (-6.583e-02) Quality = 2.406
Hessian Eigenvalues: 2.22914e-02 2.30000e-02 2.30000e-02 ... 7.88478e-01 1.48984e+00 3.47299e+01



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   7.338739   4.700404   6.452614   -0.664293  0.034860 -0.325145
   C   7.610051   3.246337   6.884645   -0.489129  0.071654 -0.257444
   C   9.033029   2.791907   6.542702   -0.420149  0.215629 -0.188881
   O   9.240794   2.820828   5.135017   -0.399340  0.194479 -0.181498
   C   8.673474   1.933158   4.225519   -0.311202  0.110356 -0.144222
   C   7.960673   0.785803   4.604202   -0.218385  0.065937 -0.100764
   C   7.376849  -0.047619   3.639209   -0.147402 -0.015352 -0.072255
   C   6.569907  -1.234904   4.104019   -0.059450 -0.066662 -0.034991
   C   7.549874   0.266490   2.269476   -0.161179 -0.042439 -0.077102
   C   8.274348   1.410208   1.911330   -0.249949  0.001006 -0.117442
   C   8.833657   2.230943   2.877714   -0.321075  0.081753 -0.147805
   C   6.965054  -0.531699   1.173086   -0.091588 -0.112031 -0.059744
   O   6.688099   0.028716   0.0

Step    5 : Displace = 2.892e-01/8.344e-01 (rms/max) Trust = 3.000e-01 (+) Grad = 5.042e-02/2.774e-01 (rms/max) E (change) = -2552.6935522392 (+7.364e-02) Quality = -1.602
Rejecting step - quality is lower than -1.0
Hessian Eigenvalues: 2.22914e-02 2.30000e-02 2.30000e-02 ... 7.88478e-01 1.48984e+00 3.47299e+01



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   7.675880   4.665750   6.624790    0.337141 -0.034654  0.172176
   C   7.869439   3.189166   7.014812    0.259389 -0.057171  0.130167
   C   9.261782   2.669428   6.634968    0.228753 -0.122479  0.092265
   O   9.456085   2.716883   5.223756    0.215291 -0.103945  0.088739
   C   8.843560   1.872929   4.294373    0.170085 -0.060229  0.068853
   C   8.087628   0.744724   4.651298    0.126954 -0.041079  0.047096
   C   7.465579  -0.046718   3.671981    0.088731  0.000901  0.032772
   C   6.617593  -1.212000   4.117628    0.047687  0.022904  0.013610
   C   7.640189   0.285688   2.305374    0.090315  0.019199  0.035898
   C   8.406145   1.410621   1.967436    0.131797  0.000413  0.056105
   C   9.003736   2.189969   2.949122    0.170079 -0.040974  0.071408
   C   7.017404  -0.475831   1.200367    0.052350  0.055868  0.027282
   O   6.751604   0.114059   0.1

Step    6 : Displace = 1.368e-01/4.066e-01 (rms/max) Trust = 1.446e-01 (x) Grad = 4.003e-02/1.770e-01 (rms/max) E (change) = -2552.7561742898 (+1.102e-02) Quality = -0.398
Hessian Eigenvalues: 2.22914e-02 2.30000e-02 2.30000e-02 ... 7.88478e-01 1.48984e+00 3.47299e+01
Maximum iterations reached (6); increase --maxiter for more


Geometry optimization failed to converge in 6 iterations
Optimization time: 779.9088201522827


In [6]:
print("\nOptimized geometry:")
print(mol_opt.atom_coords(unit="Angstrom"))


# ============================================================
# SCF calculation at optimized geometry
# ============================================================

mf_opt = scf.RHF(mol_opt)
energy = mf_opt.kernel()

print("\nOptimized SCF energy:")
print(energy)

print("\nNumber of MOs:")
print(mf_opt.mo_coeff.shape[1])

mo_coeffs = mf_opt.mo_coeff


Optimized geometry:
[[  7.6758797    4.66574958   6.62479014]
 [  7.86943945   3.18916648   7.01481179]
 [  9.26178201   2.66942829   6.6349676 ]
 [  9.45608464   2.71688271   5.22375609]
 [  8.84355953   1.87292923   4.29437269]
 [  8.08762786   0.74472413   4.65129797]
 [  7.46557918  -0.04671805   3.67198109]
 [  6.61759316  -1.21200003   4.11762804]
 [  7.64018894   0.28568822   2.30537361]
 [  8.40614513   1.41062107   1.9674359 ]
 [  9.00373557   2.1899688    2.94912204]
 [  7.01740447  -0.47583062   1.20036711]
 [  6.75160446   0.11405897   0.13060097]
 [  6.77281458  -1.84265743   1.30421951]
 [  5.7071924   -2.46016144   0.64114786]
 [  4.56360833  -1.71071737   0.36267287]
 [  3.47901018  -2.31544553  -0.25243268]
 [  3.5136862   -3.67112759  -0.60577562]
 [  2.2723277   -4.1708779   -1.24144592]
 [  2.02939796  -5.34340629  -1.84586218]
 [  0.76055763  -5.31395434  -2.26566256]
 [  0.26828564  -4.12426508  -1.90410919]
 [  1.18841551  -3.42174796  -1.27989358]
 [ -1.0926738

In [8]:
# ============================================================
# Generate orbital cube files
# ============================================================

os.makedirs(cube_folder, exist_ok=True)

resolution = 0.3

norbs = mf_opt.mo_coeff.shape[1]
n_occ = sum(mf_opt.mo_occ > 0)

orbital_filenames = []

for iorb in range(norbs):

    filename = f"{cube_folder}/orbital_{iorb}.cube"

    cubegen.orbital(
        mol_opt,
        filename,
        mf_opt.mo_coeff[:, iorb],
        resolution=resolution
    )

    orbital_filenames.append(filename)

print(f"\nGenerated {norbs} orbital cube files.")
print(f"Directory: {cube_folder}")


Generated 514 orbital cube files.
Directory: cubes_optimized


In [9]:
qm_data = {
    "mol_opt": mol_opt,
    "mo_coeff": mf_opt.mo_coeff,
    "mo_energy": mf_opt.mo_energy,
    "mo_occ": mf_opt.mo_occ,
    "e_tot": mf_opt.e_tot,
    "n_occ": int(sum(mf_opt.mo_occ > 0)),
    "cube_folder": cube_folder,
    "orbital_filenames": orbital_filenames,
}

with open(picklefile, "wb") as f:
    pickle.dump(qm_data, f)

print("Saved "+picklefile)

Saved oxazole7.pkl
