### Minimizing QM of MEOH

In [2]:
import numpy as np
from scipy.optimize import minimize
from pyscf import scf, qmmm, gto
from pyscf.tools import cubegen
from pyscf.geomopt.geometric_solver import optimize
import MDAnalysis as mda
import sys; sys.path.append('/home/chemistry/QMMM/')
import visualize_QMMM as vQ
import SCF_helpers as Sh
from importlib import reload  # Python 3.4+
import pickle
import os
import py3Dmol

In [3]:
# ============================================================
# Constants
# ============================================================

HARTREE_TO_KJMOL = 2625.49962

In [ ]:
picklefile = "MMP_QM.pkl"
cube_folder = "cubes_optimized_MEMP"

In [5]:
# Extract atom positions from System0.gro
qm_atoms, mm_coords, mm_charges, mm_names, mm_residues = Sh.read_gro(
    "../System0.gro",
    qm_residues=("MMP")
    # mm_residues=("NA", "SOL"),
)

In [4]:
# Creates a PySCF Mole object describing the quantum-mechanical system that PySCF will calculate
mol = gto.M(
    atom=qm_atoms,
    basis="sto-3g",
    charge=0,
    spin=0,
    unit="Angstrom",
    verbose=4
)

System: uname_result(system='Linux', node='Cas2', release='6.1.177-1-MANJARO', version='#1 SMP PREEMPT_DYNAMIC Sat Jul  4 22:18:29 UTC 2026', machine='x86_64')  Threads 32
Python 3.14.6 (main, Jun 15 2026, 11:36:54) [GCC 16.1.1 20260430]
numpy 2.5.1  scipy 1.18.0  h5py 3.16.0
Date: Mon Aug 24 15:23:46 2026
PySCF version 2.14.0
PySCF path  /home/chemistry/venvs/jupyter/lib/python3.14/site-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 6
[INPUT] num. electrons = 18
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = Angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 C     30.000000000000  23.300000000000  52.500000000000 AA   56.691783736952  44.030618702366  99.210621539666 Bohr   0.0
[INPUT]  2 O     31.430000000000  23.300000000000  52.500000000000 AA   59.394092095080  44.0306187023

In [5]:
# SCF calculation
mf = scf.RHF(mol)

# Geometry optimization
mol_opt = optimize(mf)

print("\nOptimized geometry:")
print(mol_opt.atom_coords(unit="Angstrom"))

Create scanner for <class 'pyscf.grad.rhf.Gradients'>
Create scanner for <class 'pyscf.scf.hf.RHF'>


geometric-optimize called with the following command line:
/home/chemistry/venvs/jupyter/lib/python3.14/site-packages/ipykernel_launcher.py -f /home/chemistry/.local/share/jupyter/runtime/kernel-f0304447-ae72-4a2d-9ace-585bdb344bc8.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.000000  23.300000  52.500000    0.000000  0.000000  0.000000
   O  31.430000  23.300000  52.500000    0.000000  0.000000  0.000000
   H  31.740000  24.220000  52.500000    0.000000  0.000000  0.000000
   H  29.640000  23.300000  53.530000    0.000000  0.000000  0.000000
   H  29.640000  22.410000  51.990000    0.000000  0.000000  0.000000
   H  29.640000  24.190000  51.990000    0.000000  0.000000  0.000000

WARN: Mole.unit (Angstrom) is changed to Bohr

New geometry
   1 C     30.000000000000  23.300000000000  52.500000000000 AA   56.691783736952  44.030618702366  99.210621539666 Bohr
   2 O     31.430000000000  23.300000000000  52.500000000000 AA   59.394092095080  44.030618702366  99.210621539666 Bohr
   3 H     31.740000000000  24.220000000000  52.500000000000 AA   59.979907193695  45.769166736966  99.210621539666 Bohr
   4 H     29.640000000000  

Step    0 : Gradient = 2.363e-02/4.259e-02 (rms/max) Energy = -113.5451799228
Hessian Eigenvalues: 2.30000e-02 5.00000e-02 5.00000e-02 ... 3.51492e-01 4.09893e-01 5.32089e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.032741  23.323072  52.504496    0.032741  0.023072  0.004496
   O  31.467075  23.249597  52.474871    0.037075 -0.050403 -0.025129
   H  31.695529  24.214719  52.517768   -0.044471 -0.005281  0.017768
   H  29.627674  23.315276  53.524401   -0.012326  0.015276 -0.005599
   H  29.662756  22.427432  51.999540    0.022756  0.017432  0.009540
   H  29.604225  24.189904  51.988924   -0.035775 -0.000096 -0.001076
New geometry
   1 C     30.032741086308  23.323072398948  52.504496310862 AA   56.753655423094  44.074219217414  99.219118335765 Bohr
   2 O     31.467075189255  23.249596660470  52.474870702836 AA   59.464154048788  43.935370194890  99.163134050322 Bohr
   3 H     31.695528643868  24.214719384845  52.517767749360 AA   59.895868510217  45.759187820553  99.244197719807 Bohr
   4 H     29.627673970044  23.315275742781  53.524401281085 AA   55.9881895

Step    1 : Displace = 4.302e-02/6.743e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 1.305e-02/2.086e-02 (rms/max) E (change) = -113.5466559227 (-1.476e-03) Quality = 0.368
Hessian Eigenvalues: 2.16857e-02 5.00000e-02 5.00000e-02 ... 3.57583e-01 4.07204e-01 5.15550e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.021071  23.312736  52.497719   -0.011671 -0.010336 -0.006777
   O  31.458983  23.273175  52.459386   -0.008093  0.023579 -0.015485
   H  31.739310  24.223179  52.543434    0.043782  0.008459  0.025666
   H  29.635136  23.316294  53.523893    0.007462  0.001018 -0.000508
   H  29.638045  22.415175  52.004262   -0.024711 -0.012257  0.004722
   H  29.597455  24.179440  51.981307   -0.006770 -0.010463 -0.007617
New geometry
   1 C     30.021070563432  23.312736409054  52.497719007873 AA   56.731601331129  44.054687027289  99.206311089253 Bohr
   2 O     31.458982515698  23.273175287087  52.459385608215 AA   59.448861112150  43.979927341590  99.133871462477 Bohr
   3 H     31.739310459404  24.223178850885  52.543433709389 AA   59.978604150817  45.775173894530  99.292699354984 Bohr
   4 H     29.635136099264  23.316293972911  53.523893123067 AA   56.0022908

Step    2 : Displace = 2.843e-02/5.161e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 3.324e-03/5.318e-03 (rms/max) E (change) = -113.5479996637 (-1.344e-03) Quality = 0.978
Hessian Eigenvalues: 1.84521e-02 5.00000e-02 5.00000e-02 ... 3.54773e-01 4.70366e-01 5.22770e-01



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.018537  23.311105  52.492217   -0.002534 -0.001631 -0.005502
   O  31.449035  23.276669  52.434051   -0.009948  0.003494 -0.025335
   H  31.722963  24.217467  52.575747   -0.016347 -0.005712  0.032314
   H  29.658019  23.327235  53.526194    0.022883  0.010941  0.002301
   H  29.636126  22.408981  52.010713   -0.001919 -0.006194  0.006452
   H  29.605320  24.178543  51.971078    0.007865 -0.000898 -0.010229
New geometry
   1 C     30.018536877107  23.311105255324  52.492216827065 AA   56.726813357889  44.051604593471  99.195913474438 Bohr
   2 O     31.449034857530  23.276669067203  52.434050874159 AA   59.430062762633  43.986529629149  99.085995753671 Bohr
   3 H     31.722963087075  24.217466687404  52.575747409852 AA   59.947712094259  45.764379469972  99.353763398931 Bohr
   4 H     29.658019021604  23.327235295014  53.526193755512 AA   56.0455333

Step    3 : Displace = 2.249e-02/3.648e-02 (rms/max) Trust = 1.414e-01 (+) Grad = 2.658e-03/5.012e-03 (rms/max) E (change) = -113.5483853116 (-3.856e-04) Quality = 1.315
Hessian Eigenvalues: 6.57553e-03 5.00000e-02 5.00000e-02 ... 3.66768e-01 4.95246e-01 6.34849e-01



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.017208  23.315552  52.480322   -0.001329  0.004446 -0.011895
   O  31.442685  23.290542  52.369626   -0.006350  0.013873 -0.064425
   H  31.719658  24.194561  52.654100   -0.003305 -0.022905  0.078353
   H  29.690896  23.352330  53.524738    0.032877  0.025095 -0.001456
   H  29.635662  22.398744  52.030540   -0.000464 -0.010237  0.019826
   H  29.583891  24.168271  51.950674   -0.021429 -0.010272 -0.020404
New geometry
   1 C     30.017208123566  23.315551611446  52.480322138752 AA   56.724302377609  44.060006988794  99.173435771189 Bohr
   2 O     31.442684980427  23.290542285455  52.369626290448 AA   59.418063233982  44.012746212111  98.964250934769 Bohr
   3 H     31.719658079531  24.194561487532  52.654100172737 AA   59.941466535161  45.721094915385  99.501828661887 Bohr
   4 H     29.690896360047  23.352330009194  53.524737678441 AA   56.1076625

Step    4 : Displace = 4.900e-02/8.165e-02 (rms/max) Trust = 2.000e-01 (+) Grad = 3.446e-03/5.972e-03 (rms/max) E (change) = -113.5489501431 (-5.648e-04) Quality = 1.488
Hessian Eigenvalues: 3.53001e-03 5.00000e-02 5.00000e-02 ... 3.61164e-01 4.98359e-01 6.75193e-01



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.018323  23.322619  52.466977    0.001115  0.007068 -0.013345
   O  31.440345  23.314434  52.306714   -0.002340  0.023892 -0.062912
   H  31.727889  24.161126  52.733013    0.008231 -0.033435  0.078913
   H  29.719981  23.377983  53.518857    0.029084  0.025653 -0.005881
   H  29.635873  22.389053  52.051463    0.000211 -0.009691  0.020924
   H  29.547589  24.154784  51.932975   -0.036302 -0.013487 -0.017699
New geometry
   1 C     30.018323242060  23.322619147815  52.466977342519 AA   56.726409646159  44.073362696907  99.148217761120 Bohr
   2 O     31.440344596934  23.314434121728  52.306714468635 AA   59.413640550154  44.057895239280  98.845364821545 Bohr
   3 H     31.727889418348  24.161126208024  52.733013232417 AA   59.957021511164  45.657911394216  99.650952732333 Bohr
   4 H     29.719980708242  23.377983181276  53.518857014593 AA   56.1626239

Step    5 : Displace = 5.170e-02/8.614e-02 (rms/max) Trust = 2.828e-01 (+) Grad = 1.047e-03/1.797e-03 (rms/max) E (change) = -113.5491663393 (-2.162e-04) Quality = 0.834
Hessian Eigenvalues: 4.80443e-03 5.00000e-02 5.00000e-02 ... 3.61380e-01 5.02280e-01 6.11282e-01



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.018777  23.321333  52.469668    0.000454 -0.001287  0.002690
   O  31.444020  23.308964  52.319961    0.003676 -0.005471  0.013246
   H  31.731490  24.170122  52.716443    0.003601  0.008996 -0.016571
   H  29.710852  23.371983  53.519215   -0.009128 -0.006000  0.000358
   H  29.633584  22.391500  52.047586   -0.002289  0.002447 -0.003878
   H  29.551276  24.156098  51.937128    0.003687  0.001314  0.004154
New geometry
   1 C     30.018777387477  23.321332566201  52.469667695045 AA   56.727267856618  44.070931410020  99.153301790574 Bohr
   2 O     31.444020204318  23.308963586379  52.319960591506 AA   59.420586441452  44.047557425716  98.870396365983 Bohr
   3 H     31.731490189751  24.170122444763  52.716442556736 AA   59.963825982953  45.674911817806  99.619638693598 Bohr
   4 H     29.710852272700  23.371983342366  53.519215248058 AA   56.1453737

Step    6 : Displace = 1.135e-02/1.893e-02 (rms/max) Trust = 3.000e-01 (+) Grad = 3.551e-04/6.192e-04 (rms/max) E (change) = -113.5491929509 (-2.661e-05) Quality = 0.982
Hessian Eigenvalues: 4.90002e-03 5.00000e-02 5.00000e-02 ... 3.61623e-01 5.36616e-01 5.76572e-01



Geometry optimization cycle 8
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  30.018770  23.321426  52.469676   -0.000008  0.000094  0.000008
   O  31.443805  23.308934  52.319549   -0.000215 -0.000029 -0.000411
   H  31.731978  24.170125  52.716745    0.000488  0.000002  0.000302
   H  29.710678  23.372048  53.519312   -0.000175  0.000065  0.000097
   H  29.633787  22.391377  52.047663    0.000203 -0.000123  0.000077
   H  29.550983  24.156090  51.937054   -0.000294 -0.000008 -0.000074
New geometry
   1 C     30.018769635379  23.321426108357  52.469676088113 AA   56.727253207276  44.071108179077  99.153317651173 Bohr
   2 O     31.443804734842  23.308934239084  52.319549425866 AA   59.420179263154  44.047501967366  98.869619375531 Bohr
   3 H     31.731978463336  24.170124617796  52.716745033466 AA   59.964748686302  45.674915924243  99.620210291776 Bohr
   4 H     29.710677739433  23.372048166122  53.519312276574 AA   56.1450439

Step    7 : Displace = 3.536e-04/5.862e-04 (rms/max) Trust = 3.000e-01 (=) Grad = 5.692e-05/1.011e-04 (rms/max) E (change) = -113.5491932541 (-3.032e-07) Quality = 0.846
Hessian Eigenvalues: 4.90002e-03 5.00000e-02 5.00000e-02 ... 3.61623e-01 5.36616e-01 5.76572e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 1.055 seconds



Optimized geometry:
[[30.01876964 23.32142611 52.46967609]
 [31.44380473 23.30893424 52.31954943]
 [31.73197846 24.17012462 52.71674503]
 [29.71067774 23.37204817 53.51931228]
 [29.63378665 22.3913766  52.04766301]
 [29.55098278 24.15609027 51.93705416]]


In [6]:
print("\nOptimized geometry:")
print(mol_opt.atom_coords(unit="Angstrom"))


# ============================================================
# SCF calculation at optimized geometry
# ============================================================

mf_opt = scf.RHF(mol_opt)
energy = mf_opt.kernel()

print("\nOptimized SCF energy:")
print(energy)

print("\nNumber of MOs:")
print(mf_opt.mo_coeff.shape[1])

mo_coeffs = mf_opt.mo_coeff


Optimized geometry:
[[30.01876964 23.32142611 52.46967609]
 [31.44380473 23.30893424 52.31954943]
 [31.73197846 24.17012462 52.71674503]
 [29.71067774 23.37204817 53.51931228]
 [29.63378665 22.3913766  52.04766301]
 [29.55098278 24.15609027 51.93705416]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
diis_damp = 0
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmp5wbn2g2z
max_memory 4000 MB (current use 324 MB)
Set gradient conv threshold to 3.16228e-05
Initial guess from minao.
init E= -113.526777737303
  HOMO = -0.30049535315709  LUMO = 0.387063180666339  gap/eV = 18.70942
cycle= 1 E= -113.487957795725  delta_E= 0.0388  |g|= 0.403  |ddm|= 2.65
  HOMO = -0.240539933645968  LUMO = 0.604455591092664  gap/eV = 22.99350
cycle= 2 E= -113.5461062766

In [7]:
# ============================================================
# Generate orbital cube files
# ============================================================

os.makedirs(cube_folder, exist_ok=True)

resolution = 0.3

norbs = mf_opt.mo_coeff.shape[1]
n_occ = sum(mf_opt.mo_occ > 0)

orbital_filenames = []

for iorb in range(norbs):

    filename = f"{cube_folder}/orbital_{iorb}.cube"

    cubegen.orbital(
        mol_opt,
        filename,
        mf_opt.mo_coeff[:, iorb],
        resolution=resolution
    )

    orbital_filenames.append(filename)

print(f"\nGenerated {norbs} orbital cube files.")
print(f"Directory: {cube_folder}")


Generated 14 orbital cube files.
Directory: cubes_optimized_MEOH


In [8]:
qm_data = {
    "mol_opt": mol_opt,
    "mo_coeff": mf_opt.mo_coeff,
    "mo_energy": mf_opt.mo_energy,
    "mo_occ": mf_opt.mo_occ,
    "e_tot": mf_opt.e_tot,
    "n_occ": int(sum(mf_opt.mo_occ > 0)),
    "cube_folder": cube_folder,
    "orbital_filenames": orbital_filenames,
}

with open(picklefile, "wb") as f:
    pickle.dump(qm_data, f)

print(picklefile)

Saved MEOH_QM.pkl
